spring:
  application:
    name: bff-service
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8585/realm/turkcell-p1-dev
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: bff-service
            client-secret: r9HPFN6HJtMDDz5xs76EGWuMOS4V00lR
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            scope:
              - openid
              - profile
              - email

server:
  port: 8989
